source 'https://rubygems.org'

gem 'sinatra'
gem 'json'
gem 'redis'
gem 'rspec'
gem 'rack-test'
gem 'activerecord', "4.0.0"
gem 'sinatra-activerecord'
gem 'slim'
gem 'pony'
gem 'logging'
gem 'rest-client'
gem 'httparty'
gem 'rake'
gem 'pg'
gem 'paperclip'
gem 'aws-sdk'
gem 'paperclip-rack'
